create extension if not exists pgcrypto;
create type public.user_role as enum ('admin','coach','student');
create table public.profiles(id uuid primary key references auth.users(id) on delete cascade,full_name text not null,role public.user_role not null default 'student',phone text,created_at timestamptz not null default now());
create table public.branches(id uuid primary key default gen_random_uuid(),name text unique not null,active boolean not null default true,created_at timestamptz not null default now());
create table public.levels(id uuid primary key default gen_random_uuid(),name text unique not null,sort_order integer not null,active boolean not null default true);
create table public.classes(id uuid primary key default gen_random_uuid(),branch_id uuid not null references public.branches(id),level_id uuid not null references public.levels(id),name text not null,active boolean not null default true,created_at timestamptz not null default now(),unique(branch_id,name));
create table public.coach_class_assignments(id uuid primary key default gen_random_uuid(),coach_id uuid not null references public.profiles(id) on delete cascade,class_id uuid not null references public.classes(id) on delete cascade,created_at timestamptz not null default now(),unique(coach_id,class_id));
create table public.student_enrollments(id uuid primary key default gen_random_uuid(),student_id uuid not null references public.profiles(id) on delete cascade,class_id uuid not null references public.classes(id) on delete cascade,active boolean not null default true,enrolled_at timestamptz not null default now());
create unique index one_active_class_per_student on public.student_enrollments(student_id) where active=true;
create table public.homework(id uuid primary key default gen_random_uuid(),class_id uuid not null references public.classes(id) on delete cascade,created_by uuid not null references public.profiles(id),title text not null,instructions text,attachment_url text,due_date date,published boolean not null default true,created_at timestamptz not null default now());
create table public.tournaments(id uuid primary key default gen_random_uuid(),title text not null,branch_id uuid references public.branches(id),venue text,starts_at timestamptz not null,registration_deadline timestamptz,description text,open_for_registration boolean not null default true,created_by uuid not null references public.profiles(id),created_at timestamptz not null default now());
create table public.tournament_registrations(id uuid primary key default gen_random_uuid(),tournament_id uuid not null references public.tournaments(id) on delete cascade,student_id uuid not null references public.profiles(id) on delete cascade,status text not null default 'registered',registered_at timestamptz not null default now(),unique(tournament_id,student_id));
insert into public.branches(name) values ('Saida'),('Beirut');
insert into public.levels(name,sort_order) values ('Starters',1),('Beginners',2),('Intermediate',3),('Advanced',4);
create or replace function public.current_role() returns public.user_role language sql stable security definer set search_path=public as $$ select role from public.profiles where id=auth.uid(); $$;
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$ select coalesce((select role='admin' from public.profiles where id=auth.uid()),false); $$;
create or replace function public.coach_has_class(target_class uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.coach_class_assignments where coach_id=auth.uid() and class_id=target_class); $$;
create or replace function public.student_has_class(target_class uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.student_enrollments where student_id=auth.uid() and class_id=target_class and active=true); $$;
alter table public.profiles enable row level security; alter table public.branches enable row level security; alter table public.levels enable row level security; alter table public.classes enable row level security; alter table public.coach_class_assignments enable row level security; alter table public.student_enrollments enable row level security; alter table public.homework enable row level security; alter table public.tournaments enable row level security; alter table public.tournament_registrations enable row level security;
create policy "profiles_self_or_admin" on public.profiles for select using(id=auth.uid() or public.is_admin());
create policy "coaches_read_assigned_students" on public.profiles for select using(public.current_role()='coach' and exists(select 1 from public.student_enrollments se join public.coach_class_assignments cca on cca.class_id=se.class_id where se.student_id=profiles.id and se.active=true and cca.coach_id=auth.uid()));
create policy "admin_all_branches" on public.branches for all using(public.is_admin()) with check(public.is_admin());
create policy "authenticated_read_branches" on public.branches for select using(auth.uid() is not null);
create policy "admin_all_levels" on public.levels for all using(public.is_admin()) with check(public.is_admin());
create policy "authenticated_read_levels" on public.levels for select using(auth.uid() is not null);
create policy "admin_all_classes" on public.classes for all using(public.is_admin()) with check(public.is_admin());
create policy "coach_read_assigned_classes" on public.classes for select using(public.coach_has_class(id));
create policy "student_read_own_class" on public.classes for select using(public.student_has_class(id));
create policy "admin_manage_coach_assignments" on public.coach_class_assignments for all using(public.is_admin()) with check(public.is_admin());
create policy "coach_read_own_assignments" on public.coach_class_assignments for select using(coach_id=auth.uid());
create policy "admin_manage_student_enrollments" on public.student_enrollments for all using(public.is_admin()) with check(public.is_admin());
create policy "student_read_own_enrollment" on public.student_enrollments for select using(student_id=auth.uid());
create policy "coach_read_class_enrollments" on public.student_enrollments for select using(public.coach_has_class(class_id));
create policy "admin_manage_homework" on public.homework for all using(public.is_admin()) with check(public.is_admin());
create policy "coach_read_assigned_homework" on public.homework for select using(public.coach_has_class(class_id));
create policy "coach_insert_assigned_homework" on public.homework for insert with check(public.current_role()='coach' and created_by=auth.uid() and public.coach_has_class(class_id));
create policy "coach_update_own_homework" on public.homework for update using(created_by=auth.uid() and public.coach_has_class(class_id)) with check(created_by=auth.uid() and public.coach_has_class(class_id));
create policy "student_read_class_homework" on public.homework for select using(published=true and public.student_has_class(class_id));
create policy "admin_manage_tournaments" on public.tournaments for all using(public.is_admin()) with check(public.is_admin());
create policy "authenticated_read_tournaments" on public.tournaments for select using(auth.uid() is not null);
create policy "admin_manage_registrations" on public.tournament_registrations for all using(public.is_admin()) with check(public.is_admin());
create policy "student_read_own_registrations" on public.tournament_registrations for select using(student_id=auth.uid());
create policy "student_register_self" on public.tournament_registrations for insert with check(student_id=auth.uid() and public.current_role()='student' and exists(select 1 from public.tournaments t where t.id=tournament_id and t.open_for_registration=true and (t.registration_deadline is null or t.registration_deadline>=now())));
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,full_name,role) values(new.id,coalesce(new.raw_user_meta_data->>'full_name',split_part(new.email,'@',1)),'student'); return new; end; $$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
